-- Bổ sung đánh giá cả lịch hẹn; khóa chính bảo đảm mỗi lịch chỉ đánh giá một lần.
CREATE TABLE IF NOT EXISTS `DANHGIALICH` (
  `MALICH` CHAR(20) NOT NULL,
  `SOSAO` INTEGER NOT NULL,
  `NHANXET` VARCHAR(500) NOT NULL,
  `TAOLUC` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`MALICH`),
  INDEX `DANHGIALICH_TAOLUC_idx` (`TAOLUC`),
  CONSTRAINT `DANHGIALICH_LICHHEN_fkey` FOREIGN KEY (`MALICH`)
    REFERENCES `LICHHEN` (`MALICH`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
