CREATE TRIGGER TRG_TuDongTaoHoaDonTuLichHenDaHoanThanh AFTER UPDATE ON LICHHEN FOR EACH ROW BEGIN
    DECLARE v_MAHD CHAR(20);
    DECLARE v_TONGTIEN INT DEFAULT 0;

    IF NEW.TRANGTHAI = 'Hoàn thành'
       AND NOT (OLD.TRANGTHAI <=> 'Hoàn thành') THEN

        SET v_MAHD = CONCAT(
            'HD', DATE_FORMAT(NOW(), '%y%m%d'),
            UPPER(SUBSTRING(REPLACE(UUID(), '-', ''), 1, 4))
        );

        SELECT COALESCE(SUM(COALESCE(SOLUONG, 0) * COALESCE(GIA_DUKIEN, 0)), 0)
          INTO v_TONGTIEN
          FROM CHITIETLICHHEN
         WHERE MALICH = NEW.MALICH;

        INSERT INTO HOADON
            (MAHD, MAKH, MALICH, MAKM, MANV, TRANGTHAI,
             TONGTIEN, HINHTHUCTHANHTOAN, NGAYTHANHTOAN)
        VALUES
            (v_MAHD, NEW.MAKH, NEW.MALICH, NULL, NULL, 'Chưa thanh toán',
             v_TONGTIEN, NULL, NOW());

        INSERT INTO CHITIETHOADON (MAHD, MADV, SOLUONG, DONGIA, THANHTIEN)
        SELECT v_MAHD, MADV, SOLUONG, GIA_DUKIEN,
               COALESCE(SOLUONG, 0) * COALESCE(GIA_DUKIEN, 0)
          FROM CHITIETLICHHEN
         WHERE MALICH = NEW.MALICH;
    END IF;
END