CREATE TRIGGER TRG_TuDongTaoHoaDonTuLichHenDaHoanThanh
AFTER UPDATE ON LICHHEN FOR EACH ROW
BEGIN
    DECLARE v_MAHD CHAR(20);
    IF NEW.TRANGTHAI = 'Hoàn thành'
       AND NOT (OLD.TRANGTHAI <=> 'Hoàn thành')
       AND NOT EXISTS (
           SELECT 1 FROM HOADON WHERE MALICH = NEW.MALICH
           AND (TRANGTHAI IS NULL OR TRANGTHAI NOT IN ('Đã huỷ', 'Đã hủy'))
       ) THEN
        SET v_MAHD = CONCAT('HD', LEFT(REPLACE(UUID(), '-', ''), 18));
        INSERT INTO HOADON (MAHD, MAKH, MALICH, TRANGTHAI, TONGTIEN, NGAYTHANHTOAN)
        SELECT v_MAHD, NEW.MAKH, NEW.MALICH, 'Chưa thanh toán',
               COALESCE(SUM(GIA_DUKIEN), 0), NULL
        FROM CHITIETLICHHEN WHERE MALICH = NEW.MALICH;
        -- GIA_DUKIEN là giá tổng của dòng, không nhân số lượng thêm lần nữa.
        INSERT INTO CHITIETHOADON (MAHD, MADV, SOLUONG, DONGIA, THANHTIEN)
        SELECT v_MAHD, MADV, COALESCE(SOLUONG, 1),
               ROUND(COALESCE(GIA_DUKIEN, 0) / GREATEST(COALESCE(SOLUONG, 1), 1)),
               COALESCE(GIA_DUKIEN, 0)
        FROM CHITIETLICHHEN WHERE MALICH = NEW.MALICH;
    END IF;
END
