-- Additive migration: preserve existing rows and constraints. Apply once.
ALTER TABLE `CHITIETLICHHEN` ADD COLUMN `PHATSINH` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `THOILUONG` INTEGER NULL;

ALTER TABLE `LICHHEN` ADD COLUMN `BATDAUTHUCTE` DATETIME(3) NULL,
    ADD COLUMN `KETTHUCDUKIEN` DATETIME(3) NULL,
    ADD COLUMN `KETTHUCTHUCTE` DATETIME(3) NULL,
    ADD COLUMN `LOAILICH` VARCHAR(20) NOT NULL DEFAULT 'DAT_TRUOC',
    ADD COLUMN `LYDOHUY` VARCHAR(200) NULL,
    ADD COLUMN `THOIGIANDEN` DATETIME(3) NULL;

CREATE TABLE `HANGDOI` (
    `MALICH` CHAR(20) NOT NULL,
    `VAOLUC` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `GOILUC` DATETIME(3) NULL,
    `TRANGTHAI` VARCHAR(20) NOT NULL DEFAULT 'CHO',

    PRIMARY KEY (`MALICH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `LICHNGHI` (
    `ID` CHAR(20) NOT NULL,
    `MANV` CHAR(20) NOT NULL,
    `BATDAU` DATETIME(3) NOT NULL,
    `KETTHUC` DATETIME(3) NOT NULL,
    `LYDO` VARCHAR(200) NOT NULL,

    INDEX `LICHNGHI_MANV_BATDAU_idx`(`MANV`, `BATDAU`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `LICHSULICH` (
    `ID` CHAR(20) NOT NULL,
    `MALICH` CHAR(20) NOT NULL,
    `NGUOISUA` CHAR(20) NOT NULL,
    `THOIDIEM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NOIDUNG` TEXT NOT NULL,

    INDEX `LICHSULICH_MALICH_THOIDIEM_idx`(`MALICH`, `THOIDIEM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `HANGDOI` ADD CONSTRAINT `HANGDOI_MALICH_fkey` FOREIGN KEY (`MALICH`) REFERENCES `LICHHEN`(`MALICH`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `LICHNGHI` ADD CONSTRAINT `LICHNGHI_MANV_fkey` FOREIGN KEY (`MANV`) REFERENCES `NHANVIEN`(`MANV`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `LICHSULICH` ADD CONSTRAINT `LICHSULICH_MALICH_fkey` FOREIGN KEY (`MALICH`) REFERENCES `LICHHEN`(`MALICH`) ON DELETE CASCADE ON UPDATE CASCADE;
